#!/usr/bin/env bash
# Displays Best School 10 times
# Display hours from 0 to 12
# Display minutes from 1 to 5
hour=0
while [ $hour -le 12 ]
do
        echo "Hour: $hour"
        minute=1
        while [ $minute -le 59 ]
        do
                echo "$minute"
                (( minute++ ))
        done
        (( hour++ ))
done
