#!/usr/bin/env bash
# Write a Bash script that stops 4-to_infinity_and_beyond process
# You must use kill

# get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinity process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
